// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SSHClosedPayload {
    "id": string;

    /** Creates a new SSHClosedPayload instance. */
    constructor($$source: Partial<SSHClosedPayload> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHClosedPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHClosedPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHClosedPayload($$parsedSource as Partial<SSHClosedPayload>);
    }
}

export class SSHDataPayload {
    "id": string;
    "data": string;

    /** Creates a new SSHDataPayload instance. */
    constructor($$source: Partial<SSHDataPayload> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHDataPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHDataPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHDataPayload($$parsedSource as Partial<SSHDataPayload>);
    }
}

export class SyncErrorPayload {
    "error": any;

    /** Creates a new SyncErrorPayload instance. */
    constructor($$source: Partial<SyncErrorPayload> = {}) {
        if (!("error" in $$source)) {
            this["error"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncErrorPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncErrorPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncErrorPayload($$parsedSource as Partial<SyncErrorPayload>);
    }
}
