// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SSHConnectionConfig {
    "id": string;
    "host": string;
    "port": number;
    "username": string;
    "password"?: string;
    "privateKey"?: string;
    "privateKeyPath"?: string;

    /** Creates a new SSHConnectionConfig instance. */
    constructor($$source: Partial<SSHConnectionConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConnectionConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConnectionConfig($$parsedSource as Partial<SSHConnectionConfig>);
    }
}
