// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

export class UIError {
    "code": string;
    "message": string;
    "apiDetails"?: api$0.ErrorDetail[];

    /** Creates a new UIError instance. */
    constructor($$source: Partial<UIError> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIError instance from a string or object.
     */
    static createFrom($$source: any = {}): UIError {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apiDetails" in $$parsedSource) {
            $$parsedSource["apiDetails"] = $$createField2_0($$parsedSource["apiDetails"]);
        }
        return new UIError($$parsedSource as Partial<UIError>);
    }
}

// Private type creation functions
const $$createType0 = api$0.ErrorDetail.createFrom;
const $$createType1 = $Create.Array($$createType0);
