// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1313366989, id);
}

export function GetAll(): $CancellablePromise<$models.Host[]> {
    return $Call.ByID(2713843469).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Save(host: $models.Host): $CancellablePromise<string> {
    return $Call.ByID(3162462591, host);
}

// Private type creation functions
const $$createType0 = $models.Host.createFrom;
const $$createType1 = $Create.Array($$createType0);
