// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2018517502, id);
}

export function GetAll(): $CancellablePromise<$models.SavedKey[]> {
    return $Call.ByID(2217667998).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Save(key: $models.SavedKey): $CancellablePromise<string> {
    return $Call.ByID(2642404940, key);
}

// Private type creation functions
const $$createType0 = $models.SavedKey.createFrom;
const $$createType1 = $Create.Array($$createType0);
