// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Host {
    "id": string;
    "type": ItemType;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "password"?: string;
    "keyId"?: string;

    /** Creates a new Host instance. */
    constructor($$source: Partial<Host> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     */
    static createFrom($$source: any = {}): Host {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Host($$parsedSource as Partial<Host>);
    }
}

export enum ItemType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeHost = "host",
    TypeKey = "key",
};

export enum KeyKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KeyKindPrivateKey = "private_key",
    KeyKindHardwareKey = "hardware_key",
};

export class SavedKey {
    "id": string;
    "type": ItemType;
    "name": string;
    "kind"?: KeyKind;
    "privateKey"?: string;
    "privateKeyPath"?: string;

    /** Creates a new SavedKey instance. */
    constructor($$source: Partial<SavedKey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ItemType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedKey instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedKey($$parsedSource as Partial<SavedKey>);
    }
}
