// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum SyncStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SyncStatusIdle = "idle",
    SyncStatusSyncing = "syncing",
    SyncStatusSuccess = "success",
    SyncStatusError = "error",
    SyncStatusUnauthenticated = "unauthenticated",
};
