// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blobs.sql

package dbgen

import (
	"context"
)

const getActiveBlobs = `-- name: GetActiveBlobs :many
SELECT id, blob, updated_at, is_deleted FROM encrypted_blobs
WHERE is_deleted = 0
`

func (q *Queries) GetActiveBlobs(ctx context.Context) ([]EncryptedBlob, error) {
	rows, err := q.db.QueryContext(ctx, getActiveBlobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncryptedBlob
	for rows.Next() {
		var i EncryptedBlob
		if err := rows.Scan(
			&i.ID,
			&i.Blob,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlobsSince = `-- name: GetBlobsSince :many
SELECT id, blob, updated_at, is_deleted FROM encrypted_blobs
WHERE updated_at > ?
`

func (q *Queries) GetBlobsSince(ctx context.Context, updatedAt string) ([]EncryptedBlob, error) {
	rows, err := q.db.QueryContext(ctx, getBlobsSince, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncryptedBlob
	for rows.Next() {
		var i EncryptedBlob
		if err := rows.Scan(
			&i.ID,
			&i.Blob,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBlob = `-- name: SoftDeleteBlob :exec
UPDATE encrypted_blobs
SET is_deleted = 1, updated_at = ?
WHERE id = ?
`

type SoftDeleteBlobParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) SoftDeleteBlob(ctx context.Context, arg SoftDeleteBlobParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteBlob, arg.UpdatedAt, arg.ID)
	return err
}

const upsertBlob = `-- name: UpsertBlob :exec
INSERT INTO encrypted_blobs (
    id, blob, updated_at, is_deleted
) VALUES (
    ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    blob = excluded.blob,
    updated_at = excluded.updated_at,
    is_deleted = excluded.is_deleted
`

type UpsertBlobParams struct {
	ID        string
	Blob      string
	UpdatedAt string
	IsDeleted bool
}

func (q *Queries) UpsertBlob(ctx context.Context, arg UpsertBlobParams) error {
	_, err := q.db.ExecContext(ctx, upsertBlob,
		arg.ID,
		arg.Blob,
		arg.UpdatedAt,
		arg.IsDeleted,
	)
	return err
}

const wipeBlobs = `-- name: WipeBlobs :exec
DELETE FROM encrypted_blobs
`

func (q *Queries) WipeBlobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, wipeBlobs)
	return err
}
