// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type EncryptedBlob struct {
	ID        string
	Blob      string
	UpdatedAt string
	IsDeleted bool
}

type User struct {
	ID                 string
	Username           string
	KeySalt            string
	AuthSalt           sql.NullString
	EncryptedMasterKey string
	ServerUrl          sql.NullString
	LastSyncTime       sql.NullString
}
