// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, username, key_salt, auth_salt, encrypted_master_key,
    server_url, last_sync_time
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	ID                 string
	Username           string
	KeySalt            string
	AuthSalt           sql.NullString
	EncryptedMasterKey string
	ServerUrl          sql.NullString
	LastSyncTime       sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.KeySalt,
		arg.AuthSalt,
		arg.EncryptedMasterKey,
		arg.ServerUrl,
		arg.LastSyncTime,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, key_salt, auth_salt, encrypted_master_key, server_url, last_sync_time FROM users LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.KeySalt,
		&i.AuthSalt,
		&i.EncryptedMasterKey,
		&i.ServerUrl,
		&i.LastSyncTime,
	)
	return i, err
}

const hasUser = `-- name: HasUser :one
SELECT COUNT(*) FROM users
`

func (q *Queries) HasUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasUser)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateUserLastSyncTime = `-- name: UpdateUserLastSyncTime :exec
UPDATE users
SET last_sync_time = ?
WHERE id = ?
`

type UpdateUserLastSyncTimeParams struct {
	LastSyncTime sql.NullString
	ID           string
}

func (q *Queries) UpdateUserLastSyncTime(ctx context.Context, arg UpdateUserLastSyncTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastSyncTime, arg.LastSyncTime, arg.ID)
	return err
}

const updateUserServerUrl = `-- name: UpdateUserServerUrl :exec
UPDATE users
SET server_url = ?, last_sync_time = ?
WHERE id = ?
`

type UpdateUserServerUrlParams struct {
	ServerUrl    sql.NullString
	LastSyncTime sql.NullString
	ID           string
}

func (q *Queries) UpdateUserServerUrl(ctx context.Context, arg UpdateUserServerUrlParams) error {
	_, err := q.db.ExecContext(ctx, updateUserServerUrl, arg.ServerUrl, arg.LastSyncTime, arg.ID)
	return err
}

const wipeUsers = `-- name: WipeUsers :exec
DELETE FROM users
`

func (q *Queries) WipeUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, wipeUsers)
	return err
}
