// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2386936566);
}

export function Maximise(): $CancellablePromise<void> {
    return $Call.ByID(2428703677);
}

export function Minimise(): $CancellablePromise<void> {
    return $Call.ByID(697000223);
}
