export enum ErrorCode {
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    RUNTIME_ERROR = "RUNTIME_ERROR",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    API_ERROR = "API_ERROR",

    NOT_FOUND = "NOT_FOUND",
    VALIDATION_FAILED = "VALIDATION_FAILED",
    DECRYPTION_FAILED = "DECRYPTION_FAILED",
    VAULT_LOCKED = "VAULT_LOCKED",
    NETWORK_FAILED = "NETWORK_FAILED",
    SSH_CONNECTION_FAILED = "SSH_CONNECTION_FAILED",
    SSH_SESSION_NOT_FOUND = "SSH_SESSION_NOT_FOUND",
}